#
#
#           admin.toml - Tolxanka administration config file.
#
#   This file defines administrative roles for Tolxanka and assigns them to
#   staff.
#



# Role - Groups together privileges and attributes to assign to staff.
# Title - Visible title shown when posting in the role of a staff member.
# Marker - A fixed character to use in place of normal Han character.
# Color - Special post header border color.
# PostWithRole - Can post in threads with staff role visible.
# ViewRestrictedTags - Can see tags restricted to normal users.
# SeeHiddenThreads - Can see threads that have been administratively hidden.
# PostInLockedThread - Can post in locked threads.
# LockThread - Can lock threads.
# StickyThread - Can sticky threads.
# DeleteThread - Can delete threads.
# DeletePost - Can delete posts.
# BanUser - Can ban users.
# BlockImage - Can block media files by hash.
# ShowUserPosts - Can use admin user query by IP functionality.
# RecommendBan - Can recommend bans for posts. (not currently implemented)
# ReceiveNotifications - Receive notifications at given email (not implemented)

[Roles.Administrator]
Title = "Admin"
Marker = "Ａ"
Color = "red"
PostWithRole = true
ViewRestrictedTags = true
SeeHiddenThreads = true
PostInLockedThread = true
LockThread = true
StickyThread = true
DeleteThread = true
DeletePost = true
BanUser = true
BlockImage = true
ShowUserPosts = true
RecommendBan = true
ReceiveNotifications = true

[Roles.Moderator]
Title = "Mod"
Marker = "Ｍ"
Color = "purple"
PostWithRole = true
ViewRestrictedTags = true
SeeHiddenThreads = true
PostInLockedThread = true
LockThread = true
StickyThread = true
DeleteThread = true
DeletePost = true
BanUser = true
BlockImage = true
ShowUserPosts = true
RecommendBan = true
ReceiveNotifications = true

[Roles.Janitor]
DeleteThread = true
DeletePost = true
BlockImage = true
RecommendBan = true
ReceiveNotifications = true

[Roles.Developer]
Title = "Developer"
Marker = "Ｄ"
Color = "blue"
PostWithRole = true
ViewRestrictedTags = true
SeeHiddenThreads = true
ShowUserPosts = true

[Roles.Bot]
Title = "Bot"
Marker = "Ｂ"
Color = "gray"
PostWithRole = true
PostSystemThreads = true


# Staff - Defines users to assign roles to.
# Role - User's assigned role.
# Active - Whether this user is currently enabled or not.
# Email - Email to use for notifications (not currently implemented).
# PublicKey - PGP public key used for authentication.

[Staff.testAdmin]
Role = "Administrator"
Active = true
Email = "xxxxxx@yyyyyyy.zzz"
PublicKey = '''
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1

AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAA
-----END PGP PUBLIC KEY BLOCK-----
'''

