#
#
#           admin.toml - Tolxanka administration config file.
#
#   This file defines administrative roles for Tolxanka and assigns them to
#   staff.
#



# Role - Groups together privileges and attributes to assign to staff.
# Title - Visible title shown when posting in the role of a staff member.
# Marker - A fixed character to use in place of normal Han character.
# Color - Special post header border color.
# PostWithRole - Can post in threads with staff role visible.
# ViewRestrictedTags - Can see tags restricted to normal users.
# SeeHiddenThreads - Can see threads that have been administratively hidden.
# PostInLockedThread - Can post in locked threads.
# LockThread - Can lock threads.
# StickyThread - Can sticky threads.
# DeleteThread - Can delete threads.
# DeletePost - Can delete posts.
# BanUser - Can ban users.
# BlockImage - Can block media files by hash.
# ShowUserPosts - Can use admin user query by IP functionality.
# RecommendBan - Can recommend bans for posts. (not currently implemented)
# ReceiveNotifications - Receive notifications at given email (not implemented)

[Roles.Administrator]
Title = "Admin"
Marker = "Ａ"
Color = "red"
PostWithRole = true
ViewRestrictedTags = true
SeeHiddenThreads = true
PostInLockedThread = true
LockThread = true
StickyThread = true
DeleteThread = true
DeletePost = true
BanUser = true
BlockImage = true
ShowUserPosts = true
RecommendBan = true
ReceiveNotifications = true

[Roles.Moderator]
Title = "Mod"
Marker = "Ｍ"
Color = "purple"
PostWithRole = true
ViewRestrictedTags = true
SeeHiddenThreads = true
PostInLockedThread = true
LockThread = true
StickyThread = true
DeleteThread = true
DeletePost = true
BanUser = true
BlockImage = true
ShowUserPosts = true
RecommendBan = true
ReceiveNotifications = true

[Roles.Janitor]
DeleteThread = true
DeletePost = true
BlockImage = true
RecommendBan = true
ReceiveNotifications = true

[Roles.Developer]
Title = "Developer"
Marker = "Ｄ"
Color = "blue"
PostWithRole = true
ViewRestrictedTags = true
SeeHiddenThreads = true
ShowUserPosts = true

[Roles.Bot]
Title = "Bot"
Marker = "Ｂ"
Color = "gray"
PostWithRole = true
PostSystemThreads = true


# Staff - Defines users to assign roles to.
# Role - User's assigned role.
# Active - Whether this user is currently enabled or not.
# Email - Email to use for notifications (not currently implemented).
# PublicKey - PGP public key used for authentication.

[Staff.nkeronkow]
Role = "Administrator"
Active = true
Email = "xxxxxx@yyyyyyy.zzz"
PublicKey = '''
-----BEGIN PGP PUBLIC KEY BLOCK-----

mQENBFf7ht0BCADHOmOSTavol9MWazNoPRAWjXnwCMFB3gc7Pn32dxTtyPSxfx0F
+Dps6diK1ZZUWGpfc1ItTcajYtHGa6KvPt8XH3Sh+F1iZJ/w93iOg7U+xQEAYMZy
X5ysLoePIZ5bKLKtRzLUTUhKzQalZC71PK0TmCPNa9PD9LFONdNGG5pZuzh36XdP
SxmbK6vtINGrS5PoyiAwoZiRYCtoeb0kJfS1BH/2Fj5IQa+B6g8L5whLXC8tTFc1
jwFnrCFpTwQpWYNHeN6O5B5+dhiX/gYG/j5+gqsqYXE1Rd3r4uAv4yis+/bwQyKH
L1+AryvZvs2cv4iwuC7UF0/+oZV5BQACga5VABEBAAG0CW5rZXJvbmtvd4kBOAQT
AQIAIgUCV/uG3QIbAwYLCQgHAwIGFQgCCQoLBBYCAwECHgECF4AACgkQpB8GKHnv
Wf6cpgf8DDBJ8f7yur53SRd/gL0ekLRhuDJt4NgdNFxk8hBinll/0EBPG2USKKMN
uNjMokYl9awzBHFRYNX6ujoiNk8VLwq77fKWpWt5YYDMawf0NI5wTk6ScCj0WaqF
5XBy4b8xOwjoiR61xyKFxrAotwbS+km8wGtPzS7O5trPuzB9SJoMkdxI9vH41oSP
WAhDTb8VmIfjvgIHw+j8J7ORkOfV3nOVCvNMnN9kc9/tWIN1Et2PDf+6qZkAYt0a
+6ZEaQ55HWhvp31vm5wnTSuIaeqXDRAB8SpEBJQOKjri3eXDNX2yKRlGUiJkbyRm
ehXfhSW2ceUsP0uNRagxMc9e0ABLXrkBDQRX+4bdAQgA3qRBLUX/TXGqlAJGHPZN
3Ogdc3HDIJeFxhgkpkyGp5nl1nrNfJhFuF2safLHgmNZzGHH7RGvpGhTpS7IqcVE
tPPKpiJkag6r40PxDXi7cec3NCNHYi1SAJs9XaiyXmDVU4bmqwAn/Ogz+x4uqp0Q
UJesw1sKwo5QQR1fzbAeBT2h3zPJ32iYhW8eUixBz0lwO2kJkXbT6dWuvxd4CzsA
dYhHJwPdDlzAq08LNnEsLKmj5sPDbsK+ICoT3sTKxIIGK9IcjTTwjH7cm6ykABji
PglAiXUiP3ts5+Hv4GI+H7HBXCK/DnCYFuevr+TIR5fxpmy0ABKWj9jhVLwAppG3
jQARAQABiQEfBBgBAgAJBQJX+4bdAhsMAAoJEKQfBih571n+2cEIAI+sFzTDJwwN
LCF7fj0Uz7MUYJSeVQW72PlaZ4UUsYBlVLpOhrGmRndKdoDGJhIbUYzRjdqBc2f8
efL0S9qY0LNIDzjGl6RKy9D9RGRvun+CL1LoHtiK0IFJ9a9vzTcy/qKJP/Jocl64
tJYiZROQGMbWVQi7/pqQGpkweHu2bmLhbktbBywfcNGPgVR2AUCr3PWdGJez2SAU
ifk41cjik335uW9vkj6ylwaCW2dnf3J7jIJ3Ysc7aIs/sI4m/gWM3TXwgrnk1OCh
SHeSdX5Ovwwu2Yw73Nx9bj5F/i3HgRO6eJAPlXmvnTNRZRE7A41Jhxkla1wpYrly
hoHWL87BYt4=
=UOYU
-----END PGP PUBLIC KEY BLOCK-----
'''

